from . import player
from . import spikey
from . import platform
from . import parrot
from . import bubble
from . import frog
from . import tiles_basic
from . import panda
from . import door
from . import fireguy
from . import robo
from . import brobo
from . import laser
from . import points
from . import blob
from . import shootbot
from . import boss
from . import fireball
from . import capsule
